Repository vignetteapp/docs, pull requests merged in 2021-10, with the labels that each got.

#9 Refine install category
  docs/install/install-methods.md
  docs/install/install-portable.md
  docs/install/install-steam.md
  docs/install/install-windows-store.md
  docs/install/prerequisites.md
Labels: documentation, hacktoberfest

#11 Add Vercel Logo
  docusaurus.config.js
Labels: enhancement, hacktoberfest

#10 Update README.md
  LICENSE
  README.md
Labels: documentation, hacktoberfest

#7 Switched over to Docusaurus from MKDocs
  .github/workflows/main.yml
  .gitignore
  LICENSE
  README.md
  babel.config.js
  docs/client/_category_.json
  docs/client/overview.md
  docs/index.md
  docs/install/_category_.json
  docs/install/install-aur.md
  docs/install/install-linux.md
  docs/install/install-methods.md
  docs/install/install-portable.md
  docs/install/install-steam.md
  docs/install/install-win.md
  docs/install/install-windows-store.md
  docs/install/prerequisites.md
  docusaurus.config.js
  mkdocs.yml
  package.json
  requirements.txt
  runtime.txt
  sidebars.js
  src/css/custom.css
  static/.nojekyll
  static/img/favicon.ico
  static/img/logo.png
  yarn.lock
Labels: documentation, enhancement, priority:medium, hacktoberfest

#14 Minor fixes
  docs/index.md
  docs/install/install-methods.md
  docs/install/install-microsoft-store.md
  docs/install/install-windows-store.md
  docusaurus.config.js
Labels: documentation, enhancement, priority:low, hacktoberfest

#16 Reword Recommended Reqs section
  docs/install/prerequisites.md
Labels: documentation, hacktoberfest

#15 feat: add hide navigation button styles
  docs/install/install-aur.md
  docs/install/install-methods.md
  docs/install/install-microsoft-store.md
  docs/install/install-portable.md
  docs/install/install-steam.md
  docusaurus.config.js
  package.json
  src/remark/disableButton.js
  static/styles/disableNavigation.css
  static/styles/disableNext.css
  static/styles/disablePrev.css
Labels: enhancement, hacktoberfest

#19 AUR and more!
  docs/client/overview.md
  docs/install/install-aur.md
  docs/install/install-microsoft-store.md
  docs/install/install-portable.md
  docs/install/install-steam.md
  static/img/install/assets.png
  static/img/install/yay-terminal-window.webp
Labels: documentation, enhancement, hacktoberfest

#20 Add tabs instead of messing with navigation
  docs/install/install-aur.md
  docs/install/install-methods.md
  docs/install/install-microsoft-store.md
  docs/install/install-portable.md
  docs/install/install-steam.md
  docusaurus.config.js
  package.json
  src/remark/disableButton.js
  static/img/install/assets.png
  static/img/install/yay-terminal-window.webp
  static/styles/disableNavigation.css
  static/styles/disableNext.css
  static/styles/disablePrev.css
Labels: enhancement, priority:medium, hacktoberfest
